test deploy to kubectl with value replacing

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -9,149 +9,156 @@ on:
 
 jobs:
   # Code
-#  editorconfig-check:
-#    name: .editorconfig lint
+  #  editorconfig-check:
+  #    name: .editorconfig lint
+  #    runs-on: ubuntu-latest
+  #    steps:
+  #      - uses: actions/checkout@v2
+  #      - uses: editorconfig-checker/action-editorconfig-checker@v1
+  #
+  #  markdown-lint:
+  #    name: markdown lint
+  #    runs-on: ubuntu-latest
+  #    steps:
+  #      - uses: actions/checkout@v2
+  #      - run: npx markdownlint-cli **/*.md
+
+#  unit_tests:
+#    name: Quality check
 #    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v2
-#      - uses: editorconfig-checker/action-editorconfig-checker@v1
-#
-#  markdown-lint:
-#    name: markdown lint
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v2
-#      - run: npx markdownlint-cli **/*.md
-
-  unit_tests:
-    name: Quality check
-    runs-on: ubuntu-latest
-#    needs: [ editorconfig-check, markdown-lint ]
-    needs: [ build ]
-    permissions:
-      id-token: write
-      contents: read
-      checks: write
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          java-version: '11'
-          distribution: 'adopt'
-      - name: Maven test
-        run: mvn -B test
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: JUnit Tests
-          path: target/surefire-reports/*.xml
-          reporter: java-junit
-
-#  #Build
-  build:
-#    needs: [ editorconfig-check, markdown-lint ]
-    runs-on: ubuntu-latest
-
-    steps:
-      - uses: actions/checkout@v3
-      - name: Set up JDK 11
-        uses: actions/setup-java@v3
-        with:
-          java-version: '11'
-          distribution: 'adopt'
-      - name: Build with Maven
-        run: |
-          mvn clean install -Dmaven.test.skip=true
-
-      - name: Upload JAR
-        uses: actions/upload-artifact@v3
-        with:
-          name: jar-artifact
-          path: target/*.jar
-          if-no-files-found: error
-          retention-days: 1
-
-#
-#
-#  # Build and push to registry
-#  push-to-registry:
+#    #    needs: [ editorconfig-check, markdown-lint ]
 #    needs: [ build ]
-#    name: Push Docker image to Docker Hub
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Check out the repo
-#        uses: actions/checkout@v3
-#
-#      - name: Log in to Docker Hub
-#        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
-#        with:
-#          username: ${{ secrets.DOCKER_USERNAME }}
-#          password: ${{ secrets.DOCKER_PASSWORD }}
-#
-#      - name: Extract metadata (tags, labels) for Docker
-#        id: meta
-#        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
-#        with:
-#          images: ${{ secrets.DOCKER_NAMESPACE }}/${{ secrets.DOCKER_REPOSITORY }}
-#          tags: |
-#            type=sha,format=long
-#
-#      - name: Download Build Artifacts
-#        uses: actions/download-artifact@v1
-#        with:
-#          name: jar-artifact
-#          path: target/
-#
-#      - name: Build and push Docker image
-#        uses: docker/build-push-action@v3
-#        with:
-#          context: .
-#          push: true
-#          tags: ${{ steps.meta.outputs.tags }}
-#          labels: ${{ steps.meta.outputs.labels }}
-#
-##      - name: Run Trivy vulnerability scanner
-##        uses: aquasecurity/trivy-action@master
-##        with:
-##          image-ref: "${{ secrets.DOCKER_NAMESPACE }}/${{ secrets.DOCKER_REPOSITORY }}:sha-${{ github.sha }}"
-##          format: "table"
-##          exit-code: "1"
-##          ignore-unfixed: true
-##          vuln-type: "os,library"
-##          severity: "CRITICAL,HIGH"
-#
-#  # Deploy
-#  deploy:
-#    needs: [push-to-registry]
-#    runs-on: ubuntu-latest
-#    outputs:
-#      service-url: ${{ steps.deploy-apprunner.outputs.service-url }}
-#
+#    permissions:
+#      id-token: write
+#      contents: read
+#      checks: write
 #    steps:
 #      - name: Checkout
-#        uses: actions/checkout@v2
+#        uses: actions/checkout@v3
 #        with:
-#          persist-credentials: false
-#
-#      - name: Configure AWS credentials
-#        id: aws-credentials
-#        uses: aws-actions/configure-aws-credentials@v1
+#          java-version: '11'
+#          distribution: 'adopt'
+#      - name: Maven test
+#        run: mvn -B test
+#      - name: Test Report
+#        uses: dorny/test-reporter@v1
+#        if: success() || failure()
 #        with:
-#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-#          aws-region: eu-west-1
+#          name: JUnit Tests
+#          path: target/surefire-reports/*.xml
+#          reporter: java-junit
+
+#  #  #Build
+#  build:
+#    #    needs: [ editorconfig-check, markdown-lint ]
+#    runs-on: ubuntu-latest
 #
-#      # The following command will update the kube config file with our cluster information.
-#      # It will use the credentials exported by the previous action.
-#      - name: Update KubeConfig
-#        shell: bash
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Set up JDK 11
+#        uses: actions/setup-java@v3
+#        with:
+#          java-version: '11'
+#          distribution: 'adopt'
+#      - name: Build with Maven
 #        run: |
-#          aws eks update-kubeconfig --name carinfo-cluster --region=eu-west-1
+#          mvn clean install -Dmaven.test.skip=true
 #
-#      # Deploy newly built changes to EKS cluster.
-#      - name: Deploy To Cluster
-#        shell: bash
-#        run: |
-#          kubectl apply -f eks/deployment.yml
-#          kubectl apply -f eks/service.yml
+#      - name: Upload JAR
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: jar-artifact
+#          path: target/*.jar
+#          if-no-files-found: error
+#          retention-days: 1
+
+  #
+  #
+  #  # Build and push to registry
+  #  push-to-registry:
+  #    needs: [ build ]
+  #    name: Push Docker image to Docker Hub
+  #    runs-on: ubuntu-latest
+  #    steps:
+  #      - name: Check out the repo
+  #        uses: actions/checkout@v3
+  #
+  #      - name: Log in to Docker Hub
+  #        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
+  #        with:
+  #          username: ${{ secrets.DOCKER_USERNAME }}
+  #          password: ${{ secrets.DOCKER_PASSWORD }}
+  #
+  #      - name: Extract metadata (tags, labels) for Docker
+  #        id: meta
+  #        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
+  #        with:
+  #          images: ${{ secrets.DOCKER_NAMESPACE }}/${{ secrets.DOCKER_REPOSITORY }}
+  #          tags: |
+  #            type=sha,format=long
+  #
+  #      - name: Download Build Artifacts
+  #        uses: actions/download-artifact@v1
+  #        with:
+  #          name: jar-artifact
+  #          path: target/
+  #
+  #      - name: Build and push Docker image
+  #        uses: docker/build-push-action@v3
+  #        with:
+  #          context: .
+  #          push: true
+  #          tags: ${{ steps.meta.outputs.tags }}
+  #          labels: ${{ steps.meta.outputs.labels }}
+  #
+  ##      - name: Run Trivy vulnerability scanner
+  ##        uses: aquasecurity/trivy-action@master
+  ##        with:
+  ##          image-ref: "${{ secrets.DOCKER_NAMESPACE }}/${{ secrets.DOCKER_REPOSITORY }}:sha-${{ github.sha }}"
+  ##          format: "table"
+  ##          exit-code: "1"
+  ##          ignore-unfixed: true
+  ##          vuln-type: "os,library"
+  ##          severity: "CRITICAL,HIGH"
+  #
+  # Deploy
+  deploy:
+    #    needs: [ push-to-registry ]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          persist-credentials: false
+
+      - name: Configure AWS credentials
+        id: aws-credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: eu-west-1
+
+      - uses: swdotcom/update-and-apply-kubernetes-configs@v1
+        with:
+          k8-config-file-paths: k8/config-staging.yaml k8/deployment.yaml
+          replacement-method: list
+          env-replacement-list: |
+            IMAGE
+        env:
+          IMAGE: lpstoyanov/car-info:sha-74d1117ce158972aa3951fa88e016cb05ad024a8
+
+
+      # The following command will update the kube config file with our cluster information.
+      # It will use the credentials exported by the previous action.
+      - name: Update KubeConfig
+        shell: bash
+        run: |
+          aws eks update-kubeconfig --name carinfo-cluster --region=eu-west-1
+
+      # Deploy newly built changes to EKS cluster.
+      - name: Deploy To Cluster
+        shell: bash
+        run: |
+          kubectl apply -f kubernetes/deployment.yml
+          kubectl apply -f kubernetes/service.yml
